# Generated by Django 4.2.30 on 2026-05-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
